language: dart
install:
  - gem install coveralls-lcov

jobs:
  include:
    - stage: analyze_and_test
      name: "SDK: stable"
      dart: "stable"
      script: make
      after_success:
        - coveralls-lcov --repo-token $COVERALLS_TOKEN coverage/lcov.info
    - stage: analyze_and_test
      name: "SDK: 2.12.2"
      dart: "2.12.2"
      script: make
    - stage: analyze_and_test
      name: "SDK: 2.10.0"
      dart: "2.10.0"
      script: make
    - stage: analyze_and_test
      name: "SDK: 2.9.3"
      dart: "2.9.3"
      script: make
    - stage: analyze_and_test
      name: "SDK: 2.8.4"
      dart: "2.8.4"
      script: make
    - stage: analyze_and_test
      name: "SDK: 2.7.2"
      dart: "2.7.2"
      script: make

stages:
  - analyze_and_test

cache:
  directories:
    - "$HOME/.pub-cache"
